# Context Lint workflow with Token Waste enforcement
# Runs on every push to main and on pull requests.
# Fails the build if the LLM readiness score drops below 60
# or if context waste exceeds 80%.
name: Context Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  context-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Context Lint
        id: lint
        uses: hanselhansel/context-cli@main
        with:
          url: 'https://your-site.com'
          fail-under: '60'
          max-context-waste: '80'
          require-llms-txt: 'true'

      - name: Check results
        run: |
          echo "Score: ${{ steps.lint.outputs.score }}"
          echo "Token Waste: ${{ steps.lint.outputs.token-waste }}%"
